# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'injectionoptions.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateModules(object):
    def setupUi(self, CreateModules):
        CreateModules.setObjectName("CreateModules")
        CreateModules.resize(1064, 663)
        self.centralwidget = QtWidgets.QWidget(CreateModules)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(820, 20, 211, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(830, 540, 171, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 621, 61))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 150, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 150, 161, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 180, 241, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 260, 241, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(430, 180, 241, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(430, 260, 241, 61))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(430, 340, 241, 61))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(430, 420, 241, 61))
        self.pushButton_8.setObjectName("pushButton_8")
        CreateModules.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CreateModules)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 21))
        self.menubar.setObjectName("menubar")
        CreateModules.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CreateModules)
        self.statusbar.setObjectName("statusbar")
        CreateModules.setStatusBar(self.statusbar)

        self.retranslateUi(CreateModules)
        QtCore.QMetaObject.connectSlotsByName(CreateModules)

    def retranslateUi(self, CreateModules):
        _translate = QtCore.QCoreApplication.translate
        CreateModules.setWindowTitle(_translate("CreateModules", "MainWindow"))
        self.pushButton.setText(_translate("CreateModules", "Import Previous Modules"))
        self.pushButton_4.setText(_translate("CreateModules", "Inject Modules"))
        self.label.setText(_translate("CreateModules", "Please create the necessary anomaly/drift modules you would like to inject in your dataset.  These modules can be reused upon creation. "))
        self.label_2.setText(_translate("CreateModules", "Create Drift Module"))
        self.label_3.setText(_translate("CreateModules", "Create Anomaly Module"))
        self.pushButton_2.setText(_translate("CreateModules", "Create Mean Drift Module"))
        self.pushButton_3.setText(_translate("CreateModules", "Create Distributional Drift Module"))
        self.pushButton_5.setText(_translate("CreateModules", "Create Point Anomaly Module"))
        self.pushButton_6.setText(_translate("CreateModules", "Create Collectve Anomaly Module"))
        self.pushButton_7.setText(_translate("CreateModules", "Create Sequential Anomaly Module"))
        self.pushButton_8.setText(_translate("CreateModules", "Create Correlation Anomaly Module"))
